/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
        Vehicle vehicleA = new Vehicle("nameA","brandA");
        Vehicle vehicleB = new Vehicle("nameB","brandB");

        vehicleA.speedUp(30);
        vehicleB.speedUp(40);

        Car carC = new Car("nameC","brandC");
        carC.speedUp(180);
        carC.speedUp(220);

        Bus carD = new Bus("nameD","brandD");
        carD.speedUp(70);
        carD.speedUp(170);

    }

}



